//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public int IDC { get; set; }
        public decimal Efectivo { get; set; }
        public decimal Trasferencia { get; set; }
        public decimal Credito { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
