//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int IDCategoria { get; set; }
        public string Categoria { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
