//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IDCliente { get; set; }
        public string Cliente { get; set; }
        public string Telefono { get; set; }
    }
}
