//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int IDProducto { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Costo { get; set; }
        public decimal StockActual { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string CodigoOficial { get; set; }
        public string CodigoInterno { get; set; }
        public int IDCategoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
