//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int ID_Detalle { get; set; }
        public int IDVenta { get; set; }
        public int IDProducto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal SubTotal { get; set; }
        public decimal CostoUnitarioVenta { get; set; }
    
        public virtual Ventas Ventas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
