//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int IDVenta { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal Total { get; set; }
        public int VentaY { get; set; }
        public int Semana { get; set; }
        public string Metodo_pago { get; set; }
    
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
